CREATE TABLE IF NOT EXISTS video(id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, name VARCHAR(30), qte INTERGER, show BOOLEAN)
CREATE TABLE IF NOT EXISTS diffusion(id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, number INTERGER, date DATE, id_video INTEGER)
CREATE TABLE IF NOT EXISTS data(cle VARCHAR(30) PRIMARY KEY, valeur VARCHAR(30))
INSERT INTO data VALUES ('lastDate','01/01/1970')